hadoop-slave1:
   image: newsparkbase
   tty: true
   container_name: hadoop-slave1
   volumes:
     - ./hadoopbase/conf:/home/hadoop/hadoop/etc/hadoop
     - ./docker-hive/conf:/home/hadoop/hive/conf
     - ./sparkbase/conf:/home/hadoop/spark/conf
   net: zoo
hadoop-slave2:
   image: newsparkbase
   tty: true
   container_name: hadoop-slave2
   volumes:
     - ./hadoopbase/conf:/home/hadoop/hadoop/etc/hadoop
     - ./docker-hive/conf:/home/hadoop/hive/conf
     - ./sparkbase/conf:/home/hadoop/spark/conf
   net: zoo
hadoop-slave3:
   image: newsparkbase
   tty: true
   container_name: hadoop-slave3
   volumes:
     - ./hadoopbase/conf:/home/hadoop/hadoop/etc/hadoop
     - ./docker-hive/conf:/home/hadoop/hive/conf
     - ./sparkbase/conf:/home/hadoop/spark/conf
   net: zoo
hadoop-master:
   image: newsparkbase
   tty: true
   container_name: hadoop-master
   volumes:
     - ./hadoopbase/conf:/home/hadoop/hadoop/etc/hadoop
     - ./docker-hive/conf:/home/hadoop/hive/conf
     - ./sparkbase/conf:/home/hadoop/spark/conf
   net: zoo
   ports:
     - "50070:50070"
     - "9083:9083"
     - "8088:8088"
     - "8080:8080"
     - "8042:8042"
   links:
     - hadoop-slave1
     - hadoop-slave2
     - hadoop-slave3
