zoo1:
   image: zookeeperbase
   restart: always
   net: zoo
   container_name: zk1
   volumes:
      - ./zookeeperbase/zoo1:/home/hadoop/zoo/data
      - ./zookeeperbase/conf:/home/hadoop/zookeeper/conf
   ports:
      - "2181:2181"
   expose:
      - "2888"
      - "3888"
zoo2:
   image: zookeeperbase
   restart: always
   net: zoo
   container_name: zk2
   volumes:
      - ./zookeeperbase/zoo2:/home/hadoop/zoo/data
      - ./zookeeperbase/conf:/home/hadoop/zookeeper/conf
   ports:
      - "2182:2181"
   expose:
      - "2888"
      - "3888"
zoo3:
   image: zookeeperbase
   restart: always
   container_name: zk3
   net: zoo
   volumes:
      - ./zookeeperbase/zoo3:/home/hadoop/zoo/data
      - ./zookeeperbase/conf:/home/hadoop/zookeeper/conf
   ports:
      - "2183:2181"
   expose:
      - "2888"
      - "3888"
zoo4:
   image: zookeeperbase
   restart: always
   container_name: zk4
   net: zoo
   volumes:
      - ./zookeeperbase/zoo4:/home/hadoop/zoo/data
      - ./zookeeperbase/conf:/home/hadoop/zookeeper/conf
   ports:
      - "2184:2181"
   expose:
      - "2888"
      - "3888"
zoo5:
   image: zookeeperbase
   restart: always
   container_name: zk5
   net: zoo
   volumes:
      - ./zookeeperbase/zoo5:/home/hadoop/zoo/data
      - ./zookeeperbase/conf:/home/hadoop/zookeeper/conf
   ports:
      - "2185:2181"
   expose:
      - "2888"
      - "3888"
